# Site wide configuration

title:            维港的烟火
locale:           en_US
url:              

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: 饼干
  avatar: manu.jpg
  bio: "finds delight in sharing happiness.. hates hatredness.. loves and supports freedom, motivating changes and righteous movements.. fan of free and open-source software movements.. has strong faith in the power of fellowship.. not a perfect human being.. but doing my best.. :)"
  email: manu.27993@gmail.com
  disqus-shortname: thetechyuga
  twitter: manu27993
  facebook: manu27993
  google:
    plus: ManuMathew0
    analytics: UA-58734190-1
    verify: I2ootfUAnnCI9vzmsSQvG1VVUH8wQYQaGSsANNa9v-g
    ad-client: 
    ad-slot: 
  bing-verify: 26A8ACD54BA466D7555B8F6F6D08B779
  github: manu-27993
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
